import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
const origin='http://127.0.0.1:3218';
test('owner API and real PostgreSQL: queue, journal, corrections and ERP fact assignment',async({page,request})=>{
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  expect((await request.get('/api/review/boards')).status()).toBe(401);
  const anon={Authorization:`Bearer ${process.env.REVIEW_TEST_ANON_JWT}`};
  for(const table of ['snapshot_photos','notification_processing','erp_order_facts']){
    const denied=await request.get(`http://127.0.0.1:54835/rest/v1/${table}`,{headers:anon});expect([401,403]).toContain(denied.status());
  }
  expect((await request.post('/api/auth',{headers:{Origin:origin},data:{password:'local-integration-password'}})).status()).toBe(200);
  await page.goto('/login?next=%2Fzhezhemon%2Fprocessing');await page.locator('input[type=password]').fill('local-integration-password');await page.locator('button[type=submit]').click();
  await expect(page).toHaveURL(/\/zhezhemon\/processing$/,{timeout:30000});
  const boardResponse=await request.get('/api/review/boards?stage=new');expect(boardResponse.status(),await boardResponse.text()).toBe(200);
  const card=(await boardResponse.json()).columns.new.cards[0];expect(card.search_name).toBe('item model');
  expect(card.photos).toContainEqual({source_url:'https://i.ebayimg.com/images/example.jpg',status:'url_only'});
  const tile=page.locator('article').first();await tile.getByRole('button',{name:/Змінити партійний номер:/}).click();
  await tile.getByRole('textbox',{name:'Партійний номер'}).fill(' manual123 ');
  await tile.getByRole('button',{name:'Зберегти',exact:true}).click();
  await expect(tile.getByText('✍️ MANUAL123 · чекає ERP',{exact:true})).toBeVisible();
  const saved=(await (await request.get('/api/review/boards?stage=new')).json()).columns.new.cards[0];
  expect(saved.manual_part_number).toBe('MANUAL123');expect(saved.part_number_version).toBeGreaterThan(0);
  await tile.getByRole('button',{name:/Змінити партійний номер:/}).click();
  await tile.getByRole('button',{name:'Очистити',exact:true}).click();await expect(tile.getByRole('textbox',{name:'Партійний номер'})).toBeHidden();
  await page.getByRole('button',{name:/Відкрити картку: An item/}).click();const panel=page.getByRole('dialog');
  await expect(panel.getByText('📦 В наявності · ≈2 шт.',{exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'✅ Купив вручну',exact:true}).click();
  await panel.getByLabel('Куплено через цю картку, шт.').fill('2');await panel.getByRole('button',{name:'Зберегти «Купив»'}).click();
  await expect(panel.getByText('Купив · вручну · 2 шт.',{exact:true})).toBeVisible();
  const manuallyBought=(await (await request.get('/api/review/boards?stage=processed')).json()).columns.processed.cards[0];
  expect(manuallyBought).toMatchObject({outcome:'bought',manual_purchase_quantity:2,manual_purchase_pending_units:2,erp_purchases:0});
  expect((await (await request.get('/api/review/boards?stage=new')).json()).columns.new.count).toBe(0);
  await panel.getByRole('button',{name:'Скасувати ручну позначку'}).click();
  await panel.getByLabel('Причина скасування «Купив»').fill('Integration correction');await panel.getByRole('button',{name:'Скасувати «Купив»',exact:true}).click();
  await expect(panel.getByText('Результату немає',{exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'🙈 Приховати до подешевшання',exact:true}).click();await expect(panel.getByRole('button',{name:'Показати знову'})).toBeVisible();
  await panel.getByRole('button',{name:'Закрити ×'}).click();await expect(page.locator('article')).toHaveCount(0);
  await page.getByRole('navigation',{name:'Розділи ZheZhemon'}).getByRole('link',{name:'Оброблені'}).click();await page.getByRole('button',{name:/Відкрити картку: An item/}).click();
  await panel.getByRole('button',{name:'Повернути в «Нові»'}).click();await panel.getByLabel('Причина виправлення').fill('Integration correction');await panel.getByRole('button',{name:'Повернути',exact:true}).click();
  await expect(panel.getByText('Результату немає',{exact:true})).toBeVisible();await panel.getByRole('button',{name:'Закрити ×'}).click();
  const from=card.sent_at.slice(0,10),emailAt=new Date(Date.parse(card.sent_at)+10*60000).toISOString();
  const fact={key:'draft:3:116897101689',ebayItemId:'116897101689',scopeDate:from,lifecycle:'draft',draftId:3,purchaseId:null,orderedAt:null,emailAt,draftCreatedAt:emailAt,purchaseCreatedAt:null,timeBasis:'email',quantity:null,cancelledUnits:0,quantityBasis:'unknown',active:true};
  const service={Authorization:`Bearer ${process.env.REVIEW_TEST_SERVICE_JWT}`};
  const synced=await request.post('http://127.0.0.1:54835/rest/v1/rpc/sync_notification_order_facts',{headers:service,data:{p_from:from,p_orders:[fact]}});expect(synced.status(),await synced.text()).toBe(200);
  await page.reload();await page.getByRole('button',{name:/Відкрити картку: An item/}).click();await expect(panel).toBeVisible();
  await expect(panel.getByText('Кількість закупленого не визначає залишок оголошення.',{exact:false})).toBeVisible();
  await panel.getByRole('button',{name:'✅ Купив вручну',exact:true}).click();
  await panel.getByLabel('Куплено через цю картку, шт.').fill('2');await panel.getByRole('button',{name:'Зберегти «Купив»'}).click();
  await expect(panel.getByText('Купив · вручну 2 шт. · звірити кількість ERP',{exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'Скасувати ручну позначку'}).click();
  await panel.getByLabel('Причина скасування «Купив»').fill('ERP exists');await panel.getByRole('button',{name:'Скасувати «Купив»',exact:true}).click();
  await expect(panel.getByText('Є підтвердження ERP. Прив’язку закупки можна виправити нижче.',{exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'Відв’язати',exact:true}).click();await expect(panel.getByRole('button',{name:'Прив’язати до цієї картки'})).toBeEnabled();
  await panel.getByRole('button',{name:'Прив’язати до цієї картки'}).click();await expect(panel.getByText('Ця картка · вручну',{exact:true})).toBeVisible();
  const issue=()=>request.post('/api/review/contexts',{headers:{Origin:origin},data:{kind:'delivery',target:card.delivery_id}});
  const contexts=await Promise.all([issue(),issue()]);const ids=await Promise.all(contexts.map(async response=>{expect(response.status()).toBe(200);return (await response.json()).id}));
  const edits=await Promise.all(ids.map(contextId=>request.post('/api/review/commands',{headers:{Origin:origin},data:{commandId:randomUUID(),contextId,action:'set_outcome',payload:{value:'funds'}}})));
  expect(edits.map(r=>r.status()).sort()).toEqual([200,409]);
  expect((await request.post('/api/review/purchases',{headers:{Origin:'https://foreign.invalid'},data:{}})).status()).toBe(403);
  expect((await request.get('/api/review/assessments')).status()).toBe(404);expect((await request.get('/api/review/reporting')).status()).toBe(404);
  await page.screenshot({path:'node_modules/.cache/stage1-real-integration.png'});
});
